config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  delete '/comments/:id', to: 'comments#destroy'
  resources :posts do
    member do
      patch 'toggle_like_feed'
      patch 'toggle_like_post'
      patch 'toggle_like_user'
      post 'new_comment_feed'
      post 'new_comment_user'
      post 'new_comment_post'
    end
  end

  get '/friend_requests', to: 'users#friend_requests'
  resources :users do
    member do
      post 'send_friend_request'
      patch 'accept_friend_request'
      put 'accept_friend_request'
      delete 'delete_friend'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
require 'bcrypt'
# User
class User < ApplicationRecord
  include BCrypt

  def password
    @password ||= Password.new(password_hash) if password_hash
  end

  def password=(new_password)
    @password = Password.create(new_password)
    self.password_hash = @password
  end
  has_attached_file :avatar,
                    styles: { medium: '150x150>', thumb: '30x30>' },
                    default_url: '/images/:style/missing.png'
  validates_attachment_content_type :avatar, content_type: %r{\Aimage\/.*\z}
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :userlikes, dependent: :destroy
  has_many :friendships, dependent: :destroy
  has_many :friends,
           -> { where(friendships: { state: 'accepted' }) },
           through: :friendships
  has_many :requested_friends,
           -> { where(friendships: { state: 'requested' }) },
           through: :friendships, source: :friend
  has_many :pending_friends,
           -> { where(friendships: { state: 'pending' }) },
           through: :friendships, source: :friend

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :handle, presence: true
  validates :password_hash, presence: true
  validate :good_email

  def full_name
    "#{first_name} #{last_name}"
  end

  def retrieve_handle
    "@#{handle}"
  end

  def send_friend_request(friend)
    b = !Friendship.exists?(user: self, friend: friend) &&
        !Friendship.exists?(user: friend, friend: self)
    return unless b
    Friendship.create(user: self, friend: friend, state: 'requested')
    u = User.find(friend.id)
    Friendship.create(user: u, friend: self, state: 'pending')
  end

  def accept_friend_request(friend)
    b = Friendship.exists?(user: friend, friend: self, state: 'requested') &&
        Friendship.exists?(user: self, friend: friend, state: 'pending')
    return unless b
    Friendship.find_by(user: friend, friend: self, state: 'requested')
              .update(state: 'accepted')
    Friendship.find_by(user: self, friend: friend, state: 'pending')
              .update(state: 'accepted')
  end

  def delete_friend(friend)
    b1 = Friendship.exists?(user: self, friend: friend)
    Friendship.find_by(user: self, friend: friend).destroy if b1
    b2 = Friendship.exists?(user: friend, friend: self)
    Friendship.find_by(user: friend, friend: self).destroy if b2
  end

  private

  def good_email
    cond = email && (email.exclude?('@') || email.exclude?('.'))
    errors.add(:email, "must have an '@' and a '.'") if cond
  end
end

app/controllers/users_controller.rb
# Users Controller
class UsersController < ApplicationController
  before_action :set_user, except: %I[index new create friend_requests]
  before_action :authenticate_user, except: %I[index show new create]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    if @user == current_user && @user.update(user_params)
      session[:user_id] = @user.id
      redirect_to @user
    else
      render :edit
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if @user == current_user
      reset_session
      @user.destroy
    end
    redirect_to users_path
  end

  def friend_requests; end

  def send_friend_request
    current_user.send_friend_request(@user)
    redirect_back(fallback_location: @user)
  end

  def accept_friend_request
    current_user.accept_friend_request(@user)
    redirect_back(fallback_location: current_user)
  end

  def delete_friend
    current_user.delete_friend(@user)
    redirect_back(fallback_location: current_user)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet.
  def user_params
    params.require(:user)
          .permit(:first_name, :last_name, :email, :password, :handle,
                  :avatar)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :handle %>
    <%= form.text_field :handle, id: :user_handle, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :user_first_name, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :user_last_name, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email, id: :user_email, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, id: :user_password, class: 'form-control' %>
  </div>

  <div class = "field form-group">
    <%= form.label 'Profile Picture' %>
    <%= form.file_field :avatar, as: :user_avatar, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit 'Submit', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class = "row">
	<div class = "col-md-3"></div>
	<div class = "col-md-6">
		<h1>Update Account Settings</h1>
		<%= render 'form', user: @user %>
	</div>
	<div class = "col-md-3"></div>

</div>


<%= link_to 'Back', @user %>

app/views/users/friend_requests.html.erb
<table class="table table-light">
  <thead>
    <tr>
      <th class="table-dark">Friend Requests</th>
      <th class="table-dark" colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% if current_user.pending_friends.empty? %>
      <td>No friend requests.</td>
    <% else %>
      <% current_user.pending_friends.each do |friend| %>
        <tr>
          <td><%= link_to friend.full_name, friend %></td>
          <td><%= link_to 'Accept Friend Request', accept_friend_request_user_path(friend), method: :patch %></td>
          <td><%= link_to 'Decline Friend Request', delete_friend_user_path(friend), method: :delete %></td>
        </tr>
      <% end %>
  <% end %>
</table>

<table class="table table-light">
  <thead>
    <tr>
      <th class="table-dark">Sent Friend Requests</th>
      <th class="table-dark" colspan="2"></th>
    </tr>
  </thead>
  <tbody>
    <% if current_user.requested_friends.empty? %>
      <td>No sent friend requests.</td>
    <% else %>
      <% current_user.requested_friends.each do |friend| %>
        <tr>
          <td><%= link_to friend.full_name, friend %></td>
          <td><%= link_to 'Cancel Friend Request', delete_friend_user_path(friend), method: :delete %></td>
          <td></td>
        </tr>
      <% end %>
  <% end %>
</table>

app/views/users/index.html.erb
<h1>Users</h1>

<table class="table table-light">
  <thead>
    <tr>
      <th class="table-dark">Name</th>
      <th class="table-dark">Email</th>
      <th class="table-dark" colspan="2">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.full_name, user %></td>
        <td><%= user.email %></td>
        <% if logged_in? && current_user == user %>
          <td><%= link_to 'Edit Profile', edit_user_path(user) %></td>
          <td><%= link_to 'Delete Account', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% elsif logged_in? && current_user.friends.include?(user) %>
          <td><%= link_to 'Remove Friend', delete_friend_user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <td></td>
        <% elsif logged_in? && current_user.requested_friends.include?(user) %>
          <td><%= link_to 'Cancel Friend Request', delete_friend_user_path(user), method: :delete, data: { confrim: 'Are you sure?' } %></td>
          <td></td>
        <% elsif logged_in? && current_user.pending_friends.include?(user) %>
          <td><%= link_to 'Accept Friend Request', accept_friend_request_user_path(user), method: :patch %></td>
          <td><%= link_to 'Decline Friend Request', delete_friend_user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% elsif logged_in? %>
          <td><%= link_to 'Send Friend Request', send_friend_request_user_path(user), method: :post %>
          <td></td>
        <% else %>
          <td></td>
          <td></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<div class = "row">
	<div class = "col-md-4"></div>
	<div class = "col-md-4">
		<h1>Create an Account!</h1>
		<%= render 'users/form', user: @user %>
	</div>
	<div class = "col-md-4"></div>

</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<div class = "row">
  <div class = "col-md-4"></div>
  <div class = "col-md-2">
    <%if @user.avatar.exists?%>
    <%= image_tag @user.avatar.url(:medium), width: '152', height: '152', class: 'avatar-display' %>
<%else%>
    <%= image_tag 'person.svg', width: '152', height: '152', class: 'avatar-display' %>
<%end%>


  </div>
  <div class = "col-md-2">
    <h1><%=@user.full_name%> (<%=@user.retrieve_handle%>)</h1>
    <p><%=@user.email%></p>
    <%if current_user == @user%>
      <%= link_to "Edit Profile", edit_user_path(@user)%>
    <%end%>
    
  </div>
  <div class = "col-md-4">
    
  </div>

</div>

<div class = "row">
  <div class = "col-md-4"></div>
  <div class = "col-md-8">
    <%if @user.posts.empty?%>
<strong>No Posts Here!</strong>
<%else%>

<%end%>
  </div>


</div>



<% if !@user.posts.empty? %>
<br>
<br>
<div class = "container">
<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-1"><a class="carousel-control-prev" href="#carouselPostControls" role="button" data-slide="prev">
    <%= image_tag 'arrow-left-b.svg', width: 30, height: 30, alt: 'send us your data please'%>
  </a></div>
  <div class="col-md-6">  <div id = "carouselPostControls" class = "carousel slide" data-ride="carousel">
  <div class = "carousel-inner">
    <% @user.posts.each do |post| %>
      <%if @user.posts.first == post%>
        <div class = "carousel-item active">
          <%= link_to post, method: :get do%>
      <%= render 'posts/post', post: post, url: "/posts/#{post.id}/new_comment_user", like_path: "/posts/#{post.id}/toggle_like_user" %>
      <%end%>
        </div>
      <%else %>
        <div class = "carousel-item">
          <%= link_to post, method: :get do%>
      <%= render 'posts/post', post: post,  url: "/posts/#{post.id}/new_comment_user", like_path: "/posts/#{post.id}/toggle_like_user"%>
      <%end%>
        </div>
      <%end%>
    <% end %>

  </div>


</div></div>
  <div class="col-md-1"><a class="carousel-control-next pull-left" href="#carouselPostControls" role="button" data-slide="next">
    <%= image_tag 'arrow-right-b.svg', width: 30, height: 30, alt: 'send us your data please'%>

  </a></div>
  <div class="col-md-2"></div>
</div>  
</div>
<%end%>