config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  delete '/comments/:id', to: 'comments#destroy'
  resources :posts do
    member do
      patch 'toggle_like_feed'
      patch 'toggle_like_post'
      patch 'toggle_like_user'
      post 'new_comment_feed'
      post 'new_comment_user'
      post 'new_comment_post'
    end
  end

  get '/friend_requests', to: 'users#friend_requests'
  resources :users do
    member do
      post 'send_friend_request'
      patch 'accept_friend_request'
      put 'accept_friend_request'
      delete 'delete_friend'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
# Post
class Post < ApplicationRecord
  belongs_to :user
  has_attached_file :image,
                    styles: { medium: '300x300>', thumb: '100x100>' },
                    default_url: '/images/:style/missing.png'
  validates_attachment_content_type :image, content_type: %r{\Aimage\/.*\z}
  validates :image, presence: true
  has_many :comments, dependent: :destroy
  has_many :userlikes, dependent: :destroy
  has_many :likes,
           -> { where(userlikes: { state: 'liked' }) },
           through: :userlikes

  def like_post(liker)
    return if Userlike.exists?(user: liker, post: self, state: 'liked')
    Userlike.create(user: liker, post: self, state: 'liked')
  end

  def unlike_post(liker)
    return unless Userlike.exists?(user: liker, post: self, state: 'liked')
    Userlike.find_by(user: liker, post: self, state: 'liked').destroy
  end

  def toggle_like(liker)
    if user_liked_post(liker)
      Userlike.find_by(user: liker, post: self, state: 'liked').destroy
    else
      Userlike.create(user: liker, post: self, state: 'liked')
    end
  end

  def user_liked_post(liker)
    Userlike.exists?(user: liker, post: self, state: 'liked')
  end
end

app/controllers/posts_controller.rb
# Posts Controller
class PostsController < ApplicationController
  before_action :set_post, except: %I[index create]

  def new_comment_feed
    ps = comment_params[:message]
    @comment = @post.comments.new(user: current_user, message: ps)
    if @comment.save
      redirect_to root_path(anchor: "post_#{@post.id}")
    else
      render :new
    end
  end

  def new_comment_user
    ps = comment_params[:message]
    @comment = @post.comments.new(user: current_user, message: ps)
    if @comment.save
      redirect_to "/users/#{@post.user.id}"
    else
      render :new
    end
  end

  def new_comment_post
    ps = comment_params[:message]
    @comment = @post.comments
                    .new(user: current_user, message: ps)
    if @comment.save
      redirect_to @post
    else
      render :new
    end
  end

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show; end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit; end

  def toggle_like_feed
    @post.toggle_like(current_user)
    redirect_to root_path(anchor: "post_#{@post.id}")
  end

  def toggle_like_user
    @post.toggle_like(current_user)
    redirect_to "/users/#{@post.user.id}"
  end

  def toggle_like_post
    @post.toggle_like(current_user)
    redirect_to post_path(@post)
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.new(post_params)
    @top_comment = @post.comments
                        .new(user: current_user, message: post_params[:caption])
    if @post.save && @top_comment.save
      redirect_to root_path
    else
      render :new
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render :edit
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    redirect_to root_path
  end

  private

  def comment_params
    params.require(:comment).permit(:message)
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Never trust parameters from the scary internet.
  def post_params
    params.require(:post).permit(:caption, :image)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class = "field form-group">
    <%=form.label :caption%>
    <%=form.text_field :caption, id: :post_caption, class: 'form-control' %>
  </div>
  <div class = "field form-group">
    <%= form.file_field :image, as: :post_image, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="card" style="width: 35rem;" id = "post_<%=post.id%>">

<span class = "card-title">

</span>

  <span class="card-title">
      <div class = col-md-1>

      </div>
      <div class = col-md-11>
    &nbsp;
    
        <strong class = 'handle-title'>
          <%if post.user.avatar.exists? %>
          <%=link_to post.user  do%>
          <%= image_tag post.user.avatar.url(:thumb), width: '30', height: '30', class: 'avatar-display' %> 

          <%end%>

          <%else%>
          <%=link_to post.user  do%>
          <%= image_tag 'person.svg', width: '30', height: '30', class: 'avatar-display' %> 

          <%end%>
          <%end%>
     &nbsp; <strong><%= link_to "#{post.user.retrieve_handle}", post %></strong>
  

      
      </strong>

      </div>
     
  </span>  

<br>
    <%= image_tag post.image.url, width: '600', height: '600', class: 'card-img display'%>

  
  

    <div class = "col-md-11">
      <h2 class = 'like-display'>
    <small class = "card-subtitle text-muted">
    <% if post.user_liked_post(current_user) %>
      <%= link_to like_path, method: :patch do%>
        <%= image_tag 'ios-heart.svg', width: 30, height: 30, alt: 'send us your data please'%>
      <%end%>
    <% else %>
      <%= link_to like_path, method: :patch do%>
        <%= image_tag 'ios-heart-outline.svg', width: 30, height: 30, alt: 'send us your data please'%>
      <%end%>
    <% end%> 
  </small>
    
  </h2>
    </div>

  <div class = "col-md-1">
    
  </div>

  <div class = "col-md-11">
      <%if Userlike.where(post: post, state: 'liked').size == 1%>
        <strong><%=Userlike.where(post: post, state: 'liked').size%> like</strong>
      <% else%>
      <strong><%=Userlike.where(post: post, state: 'liked').size%> likes</strong>
      <%end%>  
  </div>

  <div class = "col-md-1">
    
    </div>

    <div class = "col-md-11">
      <small class="card-subtitle text-muted">Updated <%= time_ago_in_words(post.updated_at) %> ago 
  <% if current_user == post.user %>
    | <%= link_to post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'card-link' do%>
      <%= image_tag 'ios-trash-outline.svg', width: 30, height: 30, alt: 'send us your data please'%>
    <%end%>
  <% end %>
  </small>

    </div>
  

   <% post.comments.each do |comment| %>
      <div class = "col-md-1">
        
      </div>

      <div class = "col-md-10">
          <strong> 
            <%=link_to_if !comment.message.empty?, comment.user.retrieve_handle, comment.user%>
            
            &nbsp;
            &nbsp;
            <small><%=comment.message if !comment.message.empty?%></small>
            <%if comment.user == current_user && !comment.message.empty?%>
      <%= link_to "/comments/#{comment.id}", method: :delete, data: {confirm: 'Are you sure?' } do%>
        <%= image_tag 'ios-close-empty.svg', width: 30, height: 30, alt: 'send us your data please'%>
      <%end%>
     <%end%>

          </strong>
      </div>

      
   <% end %>

 
<br>
  <%= render 'comments/form', :locals => {:post => post, :comment => Comment.new, :url => url}%>
  <br>
</div>
<br>
<br>
<br>

app/views/posts/edit.html.erb
<div class = "row">
	<div class = "col-md-3"></div>
	<div class = "col-md-6">
		<h1>Editing Post</h1>
		<%= render 'form', post: @post %>
		<%= link_to 'Back', @post %>
	</div>
	<div class = "col-md-3"></div>

</div>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Likes</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.likes %></td>
        <td><%= post.user %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>


<%= render 'posts/post', post: @post, url: "/posts/#{@post.id}/new_comment_post", like_path: "/posts/#{@post.id}/toggle_like_post" %>
<%if current_user == @post.user%>
<%= link_to "Edit", edit_post_path(@post)%>
<%end%>