config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  delete '/comments/:id', to: 'comments#destroy'
  resources :posts do
    member do
      patch 'toggle_like_feed'
      patch 'toggle_like_post'
      patch 'toggle_like_user'
      post 'new_comment_feed'
      post 'new_comment_user'
      post 'new_comment_post'
    end
  end

  get '/friend_requests', to: 'users#friend_requests'
  resources :users do
    member do
      post 'send_friend_request'
      patch 'accept_friend_request'
      put 'accept_friend_request'
      delete 'delete_friend'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary mb-4 head">
  <div class="container">

    <%= link_to root_path, class: 'navbar-brand' do %>
      <%= image_tag 'ig-logo.png', width: 80, height: 80, alt: 'send us your data please'%> 
    <%end%>

    <%= link_to root_path, class: 'navbar-brand' do %>
      <%= image_tag 'ig-text.svg', width: 200, height: 80, alt: 'send us your data please'%> 
    <%end%>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
            <%if !logged_in?%>
              <%= link_to users_path, class: 'nav-link' do %>
          <%= image_tag 'ios-people.svg', width: 60, height: 60, alt: 'send us your data please'%>
        <%end%>
            <%end%>
        </li>
	<%if logged_in?%>
        <%# Only display the current user's name, friend requests and log out links if a user is logged in %>
          <%= link_to users_path, class: 'nav-link' do %>
          <%= image_tag 'ios-people-outline.svg', width: 60, height: 60, alt: 'send us your data please'%>
        <%end%>
          <li class="nav-item">
            <%= link_to current_user, class: 'nav-link' do %>
              <%= image_tag 'ios-gear-outline.svg', width: 60, height: 60, alt: 'send us your data please'%>
            <%end%> 
          </li>
          <li class="nav-item"><%= link_to '/friend_requests', class: 'nav-link' do%>
              <%= image_tag 'ios-personadd-outline.svg', width: 60, height: 60, alt: 'send us your data please'%>
            <%end%>
          </li>
          <li class= "nav-item"><br></li>
          <li class = "nav-item"><br></li>
          <li class="nav-item">

            <%= link_to '/logout', method: :delete, class: 'nav-link' do%>
              <%= image_tag 'log-out.svg', width: 45, height: 45, alt: 'send us your data please'%> 
            <%end%>
          </li>
  	<%else%>
        <%# Only display the sign up and log in links if no user is logged in %>
          <li class="nav-item">

          <%= link_to new_user_path, class: 'nav-link' do%>
              <%= image_tag 'ios-personadd.svg', width: 60, height: 60, alt: 'send us your data please'%>
          <%end%>
          </li>
	  <li class="nav-item">
    <%= link_to '/login', class: 'nav-link' do%>
         <%= image_tag 'log-in.svg', width: 30, height: 30, alt: 'send us your data please'%> Login
    <%end%>
    </li>
	 <%end%>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstagramLite</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'layouts/nav'%>
    <%= yield %>
  </body>
</html>